### PR TITLE
Added option to dump parse tree to JSON

### PR DESCRIPTION
**Pull request by icefoxen**
I wanted to use Yarn from Rust, and after a week of noodling around with writing parsers I just said "well I already know how to use a REALLY GOOD JSON reading library, why don't I just modify YarnSpinner to output a parse tree as JSON?"

Of course it would be even cooler to just make the Yarn tool output the right syntax, but, eh, Javascript.

So I added a JSON output mode to YarnSpinnerConsole.  Whether or not you guys are interested in it, I don't know!  If you want, I am happy to reformat it to whatever standards you want and add unit tests, if I can figure out how to.

This did involve a little refactoring of the Loader and Dialogue objects to make it convenient, see the commit message for the first commit.

### CODE REVIEW

**Comment by icefoxen** [comment]
Ran it on all the files in `./Tests/`, it crashes on Strings.node with an unhandled exception saying "print" is not a valid function.  But, it also does that when just trying to load the node file.  Everything else it *appears* to load without issue.

Unfortunately I don't have a good way of verifying that its output is correct yet, besides doing it by eye...

**Comment by icefoxen** [comment]
Is this never going to happen then?  Has it happened already?  Is there something wrong with the PR?  Did it get implemented elsewhere?

**Comment by desplesda** [comment]
Whoa, I didn't intend to close this! This must have happened when I deleted the `development` branch; I thought I'd checked everything. My apologies. Dumping the parse tree to JSON is definitely a useful debugging and portability tool. Will see if I can restore this. (I want to merge this PR, but I want to merge the ANTLR work first.)

**Comment by desplesda** [comment]
It looks like I can't re-open this as-is; would you be able to create this PR again from your branch, but against the `master` branch? Sorry for the run-around! :(

**Comment by icefoxen** [comment]
Unfortunately I really don't have time to handle that these days.  Too busy to do much open source stuff.  :-(

**Pull request closed without merging**
