### PR TITLE
Added flags to check if we've completed a node. 

### PR DESCRIPTION
**Pull request by thebeardphantom**
Added NodeCompleted coroutine to DialogueUIBehaviour. Passed didShowOptions to help with special setups, like only showing certain node complete UI when options weren't displayed.

### CODE REVIEW

**Comment by desplesda** [comment]
Hi!

First: thanks very much for submitting a pull request! You're the first, so congrats! 

Before I can merge this, I have some comments and questions!

Do you have a specific goal in mind for being told about when a node is complete? Currently, the `DialogueRunner` notifies its client only about lines, commands, options and the dialogue ending because I didn't see a significant reason for notifying about nodes ending. From the perspective of the user, what do we gain by knowing when a node completes? (This isn't an empty question - please convince me!)

Secondly, the method of detecting when a node ends involves adding additional state to `DialogueRunner`, and inferring when a node has to have completed. This adds complexity, and increases the amount of stuff that needs to be checked when making other changes. However, there's a cleaner way of doing it: the `Dialogue`'s `Run` method internally directly detects when a node completes. See `Dialogue.cs` line 115, and also line 219.

Please don't think that I'm simply kicking this back to you! I want Yarn Spinner to be as easy as possible to maintain in the future, and keeping a close eye on architectural growth like this is something I gotta do!

Very interested to hear your thoughts on this :)

**Comment by thebeardphantom** [comment]
Well, I admit I probably could have given the deeper inner-workings a better look before settling on going with a Unity-integration-side approach. My particular integration may not be optimal, but hopefully my particular requirements make enough sense to add my changes in one way or another, as I believe they aren't too specific.

Here is a very brief clip of my dialogue system. Just by watching it you might see why I required insight into when a node ends:
https://www.youtube.com/watch?v=A2Y81bVWjYw&feature=youtu.be

My system displays options as UI buttons and no flashing continue arrow if options exist, otherwise it shows no buttons and shows the flashing continue arrow. Due to how the lines of each node are iterated on, I have no knowledge of the properties of the node in each routine (displaying the line, displaying options, etc.). If I want to show a continue arrow, and wait for any input, only when the node contains no options, this seems like the most sane and clean method of doing so. I figured that this wasn't an extraordinarily strange requirement. However, I agree that my implementation adds state (albeit local), which should be eliminated if possible as you mentioned.

**Comment by thebeardphantom** [comment]
Here's a screenshot of my dialogue setup to help understand what is going on in the video.

[

](url)

**Comment by thebeardphantom** [comment]
Actually, oh man. I'm going to close out this change, I just realized that there exists the NodeCompleteResult type. Sorry about that! Next time if I need to do a pull request I'll make sure I do my research, thanks for your time.

**Comment by desplesda** [comment]
That's ok! I'm glad that this helped to figure out how to make Yarn Spinner do what you need it to :smile:

**Comment by desplesda** [comment]
(I _would_ suggest opening a pull request that exposes the node complete event to the dialogue UI. I feel like you'll need that for your game anyway, and you've convinced me that it should be made available in general.)

**Comment by thebeardphantom** [comment]
Just so we're on the same page: I'm just changing the visibility of NodeCompleteResult to public?

**Comment by thebeardphantom** [comment]
That way you can do

`if(step is Dialogue.NodeCompleteResult)`

in DialogueRunner?

**Comment by thebeardphantom** [comment]
DialogueRunner I'll leave unchanged from commit 1c038f96e881bee4b547c69aeeb43477b4728be1.

**Comment by desplesda** [comment]
Yes, and you’d also need to add methods to DialogueUIBehaviour so that its subclasses can be told about when nodes complete.

**Pull request closed without merging**
