### PR TITLE
Small changes to build.sh script's help option

### PR DESCRIPTION
**Pull request by icefoxen**
* Prints out help when run with no arguments
 * Prints out help (once) when run with unknown arguments

### CODE REVIEW

**Comment by desplesda** [comment]
Manually merged this into `development`. Thank you very much!

**Comment by desplesda** [comment]
(GitHub shows this PR as 'closed' and not 'merged', but I did merge your contribution - I just did it manually, to put the commit into the `development` branch instead of master.)

**Comment by silasary** [comment]
For future reference, if you click the button to edit the title of a PR, it will also allow you to edit the target branch.
image

**Comment by desplesda** [comment]
Oh that's awesome! Thanks, I didn't know that.

**Pull request closed without merging**
